### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by OliverB911** [Innovana-Archived-2/OfficeUI.OLD#9]
Hello,

I like OfficeUI and want to use it in my WebApp, but the last update is 3 month ago.
I have a lot of feature-request and will be happy when you can help me:
- make the "File"-Tab working (like 1)
- add a search-box to top-right (like 3)
- add some "QuickButtons" to top-left (like 2)
- make it minimize-able (like 2)
- Tooltips (like 1)
- Hover-effect when button pressed (like 1)
- ....

(1) http://okgodoit.com/ribbon/
(2) http://acidjs.wemakesites.net/pages/ribbon-bar-xml/demo/#client-api
(3) add between

``` html
<ul role="tablist">
 <div id="searchbox" style="position:absolute; right: 0;  background-color:#eee"><input value="search"> </div> 
 <li role="tab" class="application" id="tabFile">
```

Thank you
Olli

**Comment by kdeconinck** [comment]
Hello,

First of all, thank you for being intrested in my project.
It's still in active development but I'm changing it to a AngularJS project, and I'll try to make a Pixel Perfect recreation of the Office User Interface as defined on Windows Applications.

It might take a while before it's released, but a first version should be released very quick.

Kind regards,

**Comment by kdeconinck** [comment]
The reason why you don't see any updates, it because I'm trying a lot of different things in a private repository. As soon as the project start to has it's final form, I will host it on Github.

This repository will be renamed to 'OfficeUI.BAK' and I'll create a new, clean one 'OfficeUI'. 
I hope that this suits your needs.

Kind regards,

**Comment by OliverB911** [comment]
Hi Kevin,

good to know. 

> a first version should be released very quick.

Before 02-2015?
Whats about the license for usage in commercial products? Or will be a "donation button" there?
Any public "ToDo"- or "Feature"-List where I can make comments?

I am looking forward to the new version.
Thank you
Olli

**Comment by kdeconinck** [comment]
I'm still thinking about a license to put it under for commercial products. I will also create a page somewhere where you can request features.

And I can confirm the release date before 02-2015. Do you only need the ribbon or what do you plan to use?

**Comment by OliverB911** [comment]
I have a Web-Application (www.doit-ticket.de) with a small number of customers and need to refresh the user interface. I'm was researching some Ribbon-menus, but yours is the best, because of the Office2013-style and buttons with submenus (see "New Item").

I don't need 
- the "path-navigation" ( Item -> Sub item ) 
- the menu on the left side (Blue, Orange...) 
- the "element-list". 
  Only the ribbon-menu at the top with some requests from my first post.

I want every menu-items from my app as a big icon on the ribbon-menu. So I don't need select-boxes for the font or font-size and so on... The Icons on the first tab ("Home" not "File") will be chose by the user (user-settings (use mysql-db to save configuration/order/code etc.)) - "Favoried app functions" (most used....)

More request:
- Fixed Top position when scrolling (like 1) --> ON/OFF - configurable through a configfile?
- keyboard shortcut (nice to have)
- change the tab by mouse-over instead of mouse-click  --> ON/OFF - configurable through a configfile?
- search-box at the top-right is very important (for me)

I'm not sure what will be happend when user clicked on "File". Is solution from (1) better than (2)? Or make it configurable through a configfile?

**Comment by kdeconinck** [comment]
Well, since I'm working on the project right now as a new project, I'll keep your things in mind to do first, that way you're sure that you can use it.

I would like to see your application once it's implemented to maybe use it as a showcase on the project page.

**Comment by kdeconinck** [comment]
Another thing that you need to keep in mind is that I'm creating a pixel perfect ribbon implementation, but only for Firefox. Which means that in Firefox and Outlook, the icons are at the exact same position, but, however Google Chrome and Internet Explorer might display it on another location. but should not be more than a few pixels.

**Comment by OliverB911** [comment]
Sounds very good!
See at http://www.doit-ticket.de/images/f_ui1.png or http://www.doit-ticket.de/index.php?site=funktionen.php - can show more with teamviewer if you wish.
The new UI should be a 100%-width-display-area. Feeling of a real windows-application and not of a "website".

Firefox is my number one browser, too. But I have to support IE and Chrome.
So the problem with "pixel perfect" -> it should be practical ;-)

> AngularJS

I hope there will be no conflict with jQuery and other javascript-Plugins (Chosen, Colorbox,....).

And: I want to use another context-menu (right-click), so "ON/OFF - configurable through a configfile"?

I want to be beta-tester for the new version.

**Comment by kdeconinck** [comment]
I will invite you to be a beta tester as soon as I have a first version ready.
A context menu can be possible, but one thing at a time, it's quite some complex HTML.

**Comment by OliverB911** [comment]
> A context menu can be possible,...

There is already a context menu. Right-click on the "Element 1-4"-list. :-)
I think the code for the context menu is used for the "New Item"-submenu too.

**Comment by kdeconinck** [comment]
Good evening,

I've created a new repository to hold the beta version of the ribbon. You can have a look here:
https://github.com/Kevin-De-Coninck/OfficeUI.Beta

Don't request any features yet, since it's still a very early version which means there is just a ribbon without contents. But I'm constantly workin on it, so you should see improvements come and go.

Kind regards,

**Comment by kdeconinck** [comment]
Hey,

I just want to check if you have already had a look at the Beta version of the OfficeUI.
What do you think about it?

Kind regards,

**Comment by OliverB911** [comment]
Hi Kevin,
404-error in Firefox (but the file is there) an JS-Error in IE...?
http://www.image-load.net/users/public/images/vpF2r2RCpZ.png

**Comment by kdeconinck** [comment]
It seems that Json files are not loaded correctly.
Are you sure they are being served by the browser?

Try surfing directly to the JSon file and see if you can open it. Currently, the status is still very early, some features are not implemented from this repository, while new ones have already been added.

**Comment by OliverB911** [comment]
IIS-Webserver-Security-Feature

http://webserver/OfficeUI.Beta/Resources/JSon/application.json
HTTP-Fehler 404.3 - Not Found
Die angeforderte Seite kann aufgrund einer Konfigurationserweiterung nicht angezeigt werden. Wenn es sich bei der Seite um ein Skript handelt, müssen Sie einen Handler hinzufügen. Wenn die Datei heruntergeladen werden soll, müssen Sie eine MIME-Zuordnung hinzufügen.

.json -> unknown filetype in IIS / no Handler - otherwise for downloading the correct MIME-Type is missing. = 404 File "blocked"
Rename application.json and ribbon.json to .txt and edit the sourcecode in index.html and OfficeUI.AngularJS.Controller.js --> runs fine now

Looks good, nice minimization function ;-)

**Comment by kdeconinck** [comment]
So, I'm glad it's working right now.
But you don't need to change the filetype to txt and edit the index.html files and other stuff, because the icons on the top are not showing.

In IIS, navigate to your website and click on 'MIME Types'. Make sure to add the mime type: .json here.

![image](https://cloud.githubusercontent.com/assets/3583827/5356830/21c71668-7fa1-11e4-8010-c73fc18cf272.png)

Just as showed in the image above.
When that is done and you run the original source code, you should see something like this:

![image](https://cloud.githubusercontent.com/assets/3583827/5356840/4520fd40-7fa1-11e4-866f-0355030e6786.png)

Notice the icons at the top of the ribbon which was a feature request if I'm not mistaken. So don't try to change the actual source code. The source code is working, You're having an issue with your webserver.

Contact me if you don't manage to solve that one.

Kind regards,

**Comment by OliverB911** [comment]
Hi Kevin,
happy new year!!
Any updates / news?

**Comment by kdeconinck** [comment]
Hello,

Also for you a very happy new year.
The best wishes and everything you would like for the new year.

I'm still working on the Ribbon, so I'm affraid that you can only be patient on it.
What I propose is that you create detailed issues which are feature requests. I will then implement the requested things when I feel that they fit into the project.

Keep in mind that when you create issues, that I would like to have 1 single feature request per issue and not grouped into a single issue.

Also, do write the issues in the new repository 'OfficeUI.Beta' which can be found here: https://github.com/Kevin-De-Coninck/OfficeUI.Beta

Kind regards
